version: '3.8'

services:

  mongo-db:
    image: mongo:4.2
    hostname: mongo-db
    container_name: db-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: strongpassword123
    volumes:
      - mongo-data:/data/db
    expose:
      - "27017"
    networks:
      - bike4all
    command: --auth

  orion:
    image: fiware/orion-ld:1.0.1
    container_name: fiware-orion
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG -dbuser admin -dbpwd strongpassword123
    networks:
      - bike4all

  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    environment:
      POSTGRES_DB: quantumleap
      POSTGRES_USER: quantumleap
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bike4all

  quantumleap:
    image: orchestracities/quantumleap:latest
    container_name: quantumleap
    ports:
      - "8668:8668"
    environment:
      - POSTGRES_HOST=timescaledb        
      - POSTGRES_PORT=5432                   
      - POSTGRES_DB_NAME=quantumleap      
      - POSTGRES_DB_USER=quantumleap
      - POSTGRES_DB_PASS=12345    
      - POSTGRES_USE_SSL=false
      - QL_DEFAULT_DB=timescale 
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - bike4all

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9095:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:9095
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_INSTALL_PLUGINS=yesoreyeram-boomtheme-panel
    restart: unless-stopped
    networks:
      - bike4all

networks:
  bike4all:
    driver: bridge

volumes:
  timescale-data:
  mongo-data:
  grafana_data: