version: '3.8'

services:
  bikesim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: srvb4amp2mdmpsimulator
    command: sh -c "dotnet BikeSim.dll || tail -f /dev/null"
    ports:
      - "5000:5000"
    networks:
      - bike4all

networks:
  bike4all:
    driver: bridge