version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - bike4all-2

  rabbitmq-gateway:
    build:
      context: /home/raulp/Test/Perseo
    container_name: rabbitmq-gateway
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_QUEUE=perseo_alerts
    ports:
      - "9182:9182"
    depends_on:
      - rabbitmq
    networks:
      - bike4all-2

networks:
  bike4all-2:
    driver: bridge