version: '3.8'

services:  
  orionapidotnet:
    container_name: api-inventory
    build: ./BIKE_API
    ports:
      - "7007:7007"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://0.0.0.0:7007
    networks:
      - bike4all-2
 
networks:
  bike4all-2:
    driver: bridge

